### ISSUE TITLE
infinityfix-1.1.0.jar seems to work fine on 1.16.1

### ISSUE THREAD

**Issue by calloatti** [NerdHubMC/InfinityFix#3]
infinityfix-1.1.0.jar
MC 1.16.1

https://paste.ee/p/eOHxP

Tested enchanting bow and crossbow, shooting with no arrows on inventory

![2020-06-30_10 00 46](https://user-images.githubusercontent.com/12817862/86129199-b4e6e100-bab8-11ea-848a-44bf3e59c5ba.png)

**Comment by UpcraftLP** [comment]
updated the file metadata on curseforge.
